set XPART XCK26-SFVC784-2LV-C 
set CSIM 1
set CSYNTH 1
set COSIM 1
set EXPORT_IP 1
set VIVADO_SYN 0
set VIVADO_IMPL 0
set XF_PROJ_ROOT "/mnt/HLSNAS/g110064539/OFDM_Implemented_by_HLS/project/vitis_hls_composable_project/FFT/FFT/Makefile"
set CUR_DIR "/mnt/HLSNAS/g110064539/OFDM_Implemented_by_HLS/project/vitis_hls_composable_project/FFT/FFT"
